#!/bin/bash

upstream=$(git for-each-ref --format='%(upstream:short)' "$(git symbolic-ref -q HEAD)")
branchname=$(git rev-parse --abbrev-ref HEAD)

if [[ -z $upstream ]]; then
    git push --set-upstream origin $branchname
else
    git push "$@"
fi
