#!/bin/bash
# don't commit to master!

if [[ $(git rev-parse --abbrev-ref HEAD) == 'master' ]] || [[ $(git rev-parse --abbrev-ref HEAD) == 'main' ]]; then
	echo "Don't commit to main dummy"
	echo "If you really must commit to main then run this command again with -n to skip the hook"
	exit 1
fi
