#!/bin/bash
# simple hook to check if a repo has just been freshly
# cloned.
#
# If so, it then runs my handy email-guess git script
# and tries to set the correct email for the repo
#
# see this blog post
# http://willi.am/blog/2015/02/27/dynamically-configure-your-git-email/

if [[ $1 == 00000000000* ]]; then
    git email-guess
fi

# hook that will automatically pull master and if there are new commits
# will also automatically update dependencies
git_update() {
    local current_rev=$(git rev-parse --short HEAD)

    git pull

    if git diff --name-only $current_rev..HEAD | grep -q Gemfile.lock; then
        bundle install
    fi

    if git diff --name-only $current_rev..HEAD | grep -q yarn.lock; then
        bundle exec yarn install
    fi
}

if [[ "$PWD" =~ 'special_sauce' ]] && [[ $(git rev-parse --abbrev-ref HEAD) == 'master' ]]; then
    git_update
fi
