#!/usr/bin/env bash
# Script that wraps maim to provide basic
# commands I use and make them easier to
# bind in i3 config

save_dir="$(xdg-user-dir PICTURES)"

if ! [ -d $save_dir ]; then
    mkdir -p $save_dir
fi

file_name="$save_dir/screenshot-$(date +%s).png"

cmd='maim'

case "$1" in
    --desk | -d | $NULL)
        $cmd -u "$file_name" &&
            sleep 1 &&
            notify-send "screenshot has been saved in $save_dir"
        ;;
    --window | -w)
        $cmd -ui $(xdotool getactivewindow) "$file_name" &&
            sleep 1 &&
            notify-send "screenshot has been saved in $save_dir"
        ;;
    --select | -s)
        notify-send 'select an area for the screenshot' &
        $cmd -us "$file_name" &&
            sleep 1 &&
            notify-send "screenshot has been saved in $save_dir"
        ;;
    --desk-to-clipboard | -dc)
        $cmd -u | xclip -selection clipboard -t image/png &&
            sleep 1 &&
            notify-send "screenshot has been copied to clipboard"
        ;;
    --window-to-clipboard | -wc)
        $cmd -ui $(xdotool getactivewindow) | xclip -selection clipboard -t image/png &&
            sleep 1 &&
            notify-send "screenshot has been copied to clipboard"
        ;;
    --select-to-clipboard | -sc)
        notify-send 'select an area for the screenshot' &
        $cmd -us | xclip -selection clipboard -t image/png &&
            sleep 1 &&
            notify-send "screenshot has been copied to clipboard"
        ;;
    --help | -h)
        echo "
available options:
-d  | --desk                  full screen
-w  | --window                active window
-s  | --select                selection
-dc | --desk-to-clipboard     full screen to clipboard
-wc | --window-to-clipboard   active window to clipboard
-sc | --select-to-clipboard   selection to clipboard
-h  | --help                  display this information

Default option is 'full screen'.
Images will be saved to $save_dir
"
        ;;
    *)
        echo "
== ! missing or wrong argument ! ==

available options:
-d  | --desk                  full screen
-w  | --window                active window
-s  | --select                selection
-dc | --desk-to-clipboard     full screen to clipboard
-wc | --window-to-clipboard   active window to clipboard
-sc | --select-to-clipboard   selection to clipboard
-h  | --help                  display this information

Default option is 'full screen'.
Images will be saved to $save_dir
"

        exit 2
        ;;
esac

exit 0
