#!/bin/bash
# symlink git hooks to /usr/local/bin

dir=$DOTFILES/scripts/git/hooks
git_dir=$(dpkg -L git | grep -m 1 templates)/hooks
files="post-checkout"

# link the hooks
for file in $files; do
  echo "Creating symlink for $file"
  sudo ln -s $dir/$file $git_dir
done

echo "Done"
