autoload -U compinit && compinit

autoload -Uz $DOTFILES/functions/*(:t)

source $NVM_DIR/nvm.sh

source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

source $DOTFILES/secrets

source /etc/zsh_command_not_found

eval "$(direnv hook zsh)"

eval "$(rbenv init -)"

path+=$DOTFILES/scripts/bash

fpath=($DOTFILES/functions $fpath)
