export DOTFILES=~/.dotfiles.d

export NVM_DIR=~/.nvm

export GOPATH=~/.go_path

export EDITOR=/usr/bin/vim

export LS_COLORS='di=1;34:ln=35:so=32:pi=33:ex=1;31:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;43'

source $NVM_DIR/nvm.sh

source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

source $DOTFILES/secrets

source /etc/zsh_command_not_found

path+=$DOTFILES/scripts/bash

fpath=($DOTFILES/functions $fpath)
