import = ["~/.config/alacritty/solarized_light.toml"]
live_config_reload = true

[font]
normal = {family = "Hack Nerd Font"}
size = 11.0


[keyboard]
bindings = [
{action = "CreateNewWindow", key = "R", mods = "Shift|Control"},
{action = "ToggleFullscreen", key = "F11"}
]

[scrolling]
history = 10000

[window.padding]
x = 3
y = 3
