#!/bin/bash

case ${1} in
"s")
  vars=$(heroku config -a special-sauce-staging --json)
  username=$(echo ${vars} | jq -r '.MONGO_USERNAME')
  password=$(echo ${vars} | jq -r '.MONGO_PASSWORD')
  uri=$(echo ${vars} | jq -r '.MONGO_URI')
  string="mongodb+srv://${username}:${password}@${uri}"
  ;;
"a")
  if [ -z "$REPORTING_ANALYTICS_PW" ]; then
    echo "Error: REPORTING_ANALYTICS_PW environment variable is not set"
    exit 1
  fi
  string="mongodb+srv://reporting-analytics-pod:${REPORTING_ANALYTICS_PW}@reportingandanalyticspo.m5get.mongodb.net/bonusly_production"
  ;;
*)
  exit 1
  ;;
esac

sed -i "s|uri: <%= \"mongodb://localhost[^\"]*\" %>|uri: $string|" "$(git rev-parse --show-toplevel)/config/mongoid.yml"
